.vs/ProjectSettings.json, .vs/VSWorkspaceState.json, source/dxgi/dxgi_swapchain.cpp
Some newer games will issue `IDXGISwapChain*::Present* (...)` using the flag `DXGI_PRESENT_TEST`.
When these calls are encountered, they are not actually presenting anything. This is a status inquiry similar to D3D9's cooperative level to check for device reset, and may be used to test swapchain latency, a partially covered window and various other  things prior to drawing anything.
These calls ***should not*** be passed through ReShade's render pipeline, they should be ignored and passed directly to the DXGI runtime. Framerate counting, performance and stability will suffer in games like Deus Ex: Mankind Divided if software fails to ignore these calls.
=> Fix for games that use DXGI Present testing

source/opengl/opengl.cpp
This fixes a startup issue in KOF XIV when ReShade is compiled in Debug as described here:
https://reshade.me/forum/troubleshooting/3194-the-king-of-fighters-xiv-cbt-black-screen-issue
technically, `attribs` could stay as an array of 7 entries for Release builds but IMO it doesn't matter.
=> Fix wglCreateContextAttribsARB flow in debug builds

source/com_ptr.hpp, source/d3d10/d3d10_effect_compiler.cpp, source/d3d11/d3d11_effect_compiler.cpp, source/d3d9/d3d9_runtime.cpp, source/directory_watcher.cpp, source/filesystem.hpp, source/lexer.cpp, source/opengl/opengl_effect_compiler.cpp, source/opengl/opengl_effect_compiler.hpp, source/opengl/opengl_runtime.cpp, source/opengl/opengl_runtime.hpp, source/runtime.cpp, source/runtime_objects.hpp
I changed quite a few things:
1. Changed uniform storage variables to GL*ptr variables - they are created from natural word size variables (used to be truncated) and used as parameters where GL functions expect GLptr variables - so figured this will make 32-bit and 64-bit OpenGL implementation more consistent.
2. Added more move semantics.
3. Merged and altered a fix from @bacondither, as mentioned in KOF topic on ReShade forums:
https://github.com/bacondither/reshade/commit/81c607e49269f843c7b02f494b62de0e9a9d9463
I preserved the check, albeit with fixed conditions.
I also planned to port some of the changes made in d3d8to9 over the last couple of months - mainly interlocked refcounting. However, I guess I'll push this separately given 3. is a quite major bugfix, making ReShade usable in …
=> Fix for KOF CBT black screen + more

source/runtime.hpp
I'm color blind and was having a lot of trouble telling whether a checkbox was checked.
This is a contrast tweak.
=> Change default `active` color to contrast more

source/runtime.cpp, source/runtime.hpp, source/variant.hpp
Significantly improves startup time in performance mode with a full shaders checkout.
This makes it more feasible to share a single shaders directory for all games since unused effects won't get loaded.
I did change the preset file format slightly though, so newer versions wouldn't properly load with an old preset file. The solution would be to simply turn off performance mode once, re-enable the desired effects, then turn performance mode back on.
I'll remove the cleanup commit if you want. It was originally part of some changes that were relevant to the PR, but the final solution didn't use them. I left it in because I still think it improves the code, but it doesn't really matter.
=> Only load enabled effects in performance mode

source/runtime.cpp
Just added a static_cast because warnings annoy me.
ImGuiListClipper clipper(static_cast<int>(lines.size()), ImGui::GetTextLineHeightWithSpacing());
=> remove implicit cast warning

source/d3d11/d3d11.cpp, source/d3d11/d3d11_device_context.cpp, source/d3d11/d3d11_runtime.cpp, source/d3d11/d3d11_runtime.hpp, source/runtime.cpp, source/runtime.hpp
Moves the tabs in the menu into a dynamic list. Subclasses, or other objects with a reference to runtime can call a function to add a label (like "DX11") and function (`dx11_runtime::draw_dx11_menu()`) to draw the menu. This will allows library-specific configuration displays.
In addition, the load_configuration and save_configuration functions can be subscribed to. This allows subclasses (and plugins) to have specific configuration. In the case of DX11, it allows the debug buffer menu to be drawn to a special tab, and the two dx11 specific settings to be housed in the dx11_runtime class.
A possible breaking change (that isn't that important) is I renamed the BUFFER_DETECTION section in the config file to DX11_BUFFER_DETECTION to be more accurate.
=> Dynamic menu

source/d3d11/d3d11.cpp, source/d3d11/d3d11_device_context.cpp, source/d3d11/d3d11_device_context.hpp, source/d3d11/d3d11_runtime.cpp, source/d3d11/draw_call_tracker.cpp, source/d3d11/draw_call_tracker.hpp
The primary goal of this pull request is to set the groundwork for capturing additional buffers useful for post processing shaders. In the future, Reshade could pass surface normals and/or camera transforms to the post processing shaders for things like ambient occlusion and temporal aliasing. A little more work needs to be done to this effect (heuristics and config options) - but this represents the back-end component
- I wasn't able to test this on deferred context pipelines... but I don't think there should be any issues. It would be ideal if we could test that before merging into master
- pointers to intermediate buffers that are drawn along side depth buffers are stored in a "snapshot"
- pointers to constant buffers that are mapped along side depth buffers are stored
- the …
=> draw_call_tracker now tracks intermediate buffers (normals, motion vectors, etc) and constant buffers

source/gui.cpp, source/ini_file.cpp, source/ini_file.hpp, source/runtime.cpp, source/runtime.hpp
ReShade64 2018-10-13 20-55-14
**[x]** Include Preset (\*.ini)
**[ ]** Include Configuration (*.ini)
ReShade64 2018-10-13 20-55-17
**[x]** Include Preset (\*.ini)
**[x]** Include Configuration (*.ini)
=> Add option to save preset and configuration at screenshot

source/input.cpp
If exist these settings
* S
* Ctrl + S
* Ctrl + Shift + S
If you pressed key combination "Ctrl + Shift + S", switches these effects at the same time.
=> Fix a problem that key binding condition is wrong

source/gui.cpp
So it is less likely to loose shots when something is not set up correctly (typo in the screenshot path, folder structure changed, etc.)
=> Add warning to home page if the screenshot directory doesn't exist

source/runtime.cpp
https://reshade.me/forum/general-discussion/5081-not-applied-default-bool-uniform-on-dx9-configmode
=> Fix that reset of boolean uniform is not supported

source/d3d9/d3d9_device.cpp, source/d3d9/runtime_d3d9.cpp, source/d3d9/runtime_d3d9.hpp
Found that, filtering the viewport, i can get rid of the parasite depth buffer drawcalls that can occur in some games (Outlast, Half-life 2, Mass Effect 2 cinematics...). Feel free to check it, Crosire ;-)
=> fix parasite D3D9 depth buffers

source/d3d9/d3d9_device.cpp, source/d3d9/runtime_d3d9.cpp, source/d3d9/runtime_d3d9.hpp
Many settings are now unnecessary (the ability to choose between the number of vertices and the number of drawcalls in autopreserve mode), and the checkbox called "Disable the depth buffer size restriction" is removed, because ths setting is configured dynamically during the detection process.
=> remove unnecessary settings + fix Vanquish shadows

source/d3d9/d3d9_device.cpp, source/d3d9/runtime_d3d9.cpp, source/d3d9/runtime_d3d9.hpp
Check that the drawcall is done on the good depthstencil (the one from which the depthstencil_replaceent was created)
=> Add associated depthstencil check

source/gui.cpp, source/runtime.cpp, source/runtime.hpp
This proposal is reimplement of #100
This request contains
* Add prev/next button
* Change contant of preset path to stem
* Highlight current preset in selectable items ~and can not select it~
=> Add prev/next buttons for preset explorer

source/effect_codegen.hpp
For some reason v142 toolset complains about std missing unique_ptr unless `#include <memory>`  is added to `effect_codegen.hpp`. I'm not sure this is the right include place but figured a pull is better than a issue report. There's still a lot more kinks to work out for v142 toolset but my local ricer branch seems to run fine, albeit with modified props to suppress errors and cool it's heels.
I don't think this is an issue with VS2019 having a newer "std:latest" standard since I also explicitly tested /std:c++17
Other than loads of deprecations and other warnings,  `Release App|Win32` and `Release App|x64` seem to be the only configurations which fail to compile (though there's likely a lot more corner cases, i.e. runtime_opengl* and probably some libs needing updating).
Forgive the 3am …
=> effect_codegen.hpp: #Include <memory> (fixes VS2019/v142 build failures)

source/gui.cpp, source/runtime.cpp, source/runtime.hpp
This patch allows ReShade to save a clean image before rendering effects by moving the `save_screenshot` call to the `update_and_render_effects` subroutine when the option is selected. The benefit of this is having before-and-after screenshots on the same frame, allowing you to see the effects of the shaders with no changes from the game.
This modifies the signature for `save_screenshot()` into `save_screenshot(bool)` to accomodate for the `-before` and `-after` suffix on the screenshot filename.
=> Add support for saving  before and after screenshots on the same frame

source/d3d10/d3d10_device.cpp, source/d3d10/draw_call_tracker.cpp, source/d3d11/d3d11_device_context.cpp, source/d3d11/draw_call_tracker.cpp, source/d3d12/d3d12_device.cpp, source/d3d12/draw_call_tracker.cpp
In some D3D12 games (for instance, FIFA 19), Reshade crashes when trying to create a graphic pipeline state, or a new shader resource view based on the depth image.
This is due to the fact that the depth image resource was created with the D3D12_RESOURCE_FLAG_DENY_SHADER_RESOURCE flag. It not only disallows the shader access to this resource, it also crashes the CreateShaderResourceView method or the CreateGraphicsPipelineState method.
Now, FIFA 19 D3D12 has a proper access to depth buffer without crashing. As it is a Frostbite 3 game, maybe this fix can be usefull for some other D3D12 games ;-)
=> !!! BUGFIX !!! Force depth texture access to shader in d3d12

source/gui.cpp
Windows OS uses binary prefix.
=> Change to displaying size bytes with binary prefix

source/gui.cpp, source/runtime.cpp, source/runtime.hpp
Added shortcut keys for switching backward or forward between presets. They can be configured in the settings page jut below "Effect Toggle Key". Also the switching is no longer circular, It does not go directly from the last to the first preset anymore. For example: when using depth of field filter with manual focus and  want to quickly go to the last preset (or the first), it will no longer go circular if pressing the shortcut key once more by accident.
There aren't so many changes in code as the git is showing, because there was a re-indentation of a  big block of c ode (which I think I could avoid it in fact, sorry for that)
=> Shortcut keys for switching backward or forward between presets

source/dllmain.cpp
Implements RESHADE_MODULE_PATH_OVERRIDE:
Override the ReShade system module path to one they choose.
This is useful for if users want to use DirectX re-implementations such as D9VK or DXVK alongside ReShade.
=> Implement module path override env var

source/effect_expression.cpp, source/effect_preprocessor.cpp
std::fmod with float arguments should be the same as std::fmodf, for some reason gcc has no std::fmodf.
=> fix issues with building on gcc

source/d3d11/d3d11.cpp, source/dxgi/dxgi_swapchain.cpp
Basically, detect if the call to D3D11CreateDevice is coming from the DXGI / D3D runtime itself via WDDM and in this case do _not_ return a proxy D3D11 device.
=> Fix for hooking DXGI on D3D multi-gpu and Optimus systems.

source/runtime.cpp, source/runtime.hpp, source/runtime_gui.cpp
I found out that `stbi_image_write` does support JPEG compression, so it was pretty easy to add support for the format.
Upon testing it seems to work just fine, I've also added it to the UI, with a quality slider (from 1 to 100) that shows up when the JPEG format is selected.
It actually appears to save faster than PNG with lower file sizes, even at 100 quality, so that's nice.
I've also hidden the clear alpha option from the GUI when JPEG is selected and modified `reshade::runtime::save_screenshot()` so that the alpha isn't cleared if JPEG is selected, since stbi automatically ignores the alpha channel.
=> Added JPEG as a screenshot format option.

source/hook_manager.cpp
`hook::apply_queued_actions()` was getting called immediately for `queue_enable == true` (probably not important, but it does cause every thread in the process to be suspended every time a single hook is installed)
=> Fixed hook queuing flag

source/runtime.cpp, source/runtime.hpp, source/runtime_gui.cpp, source/runtime_objects.hpp
The second commit is optional. User can check who read and wrote it.
=> Change the type of variable used to manage shared textures

source/runtime_gui.cpp
This fixes the issue in e.g. WatchDogs Legion where the mouse is in a tiny rectangle due to the game's use of ClipCursor. Adding a call to ClipCursor(nullptr) solves this. The solution implemented isn't checking whether it's necessary to reset it to the full desktop so in the future it might be necessary for some games which can't deal with this to first call GetClipCursor to determine the current active clip cursor area, compare that to the client area of the window of the active hWnd imgui is rendering to and if the clipcursor area is smaller, call ClipCursor(nullptr).
=> Fixes issue with mouse staying in a tiny box when the overlay was opened in some games

source/d3d10/runtime_d3d10.cpp, source/d3d11/runtime_d3d11.cpp, source/opengl/runtime_gl.cpp, source/runtime.cpp, source/runtime.hpp, source/runtime_gui.cpp, source/vulkan/runtime_vk.cpp
There is currently a long-standing bug in the NVIDIA driver where any kind of frame profiling can cause sudden frame drops/spikes in VR, making the playing experience choppy and rather unpleasant. I've had at least one report where ReShade caused this issue with Skyrim VR.
Therefore, I added a config option to disable GPU performance queries. I don't know if this feature is useful beyond circumventing this particular driver bug. But until NVIDIA finally fixes it, some VR users would probably need it to actually be able to use ReShade, so I thought I'd at least post it here for consideration if NVIDIA keeps taking their time.
For reference: https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/402768/valve-index-missing-dropped-frames-since-nvidia-d/
=> Add config option to disable GPU statistics gathering

res/exports.def, source/d3d11/runtime_d3d11.cpp, source/openvr/openvr.cpp
PR to open discussion for AMS2 VR.
These are a few changes to enable ReShade to work on Automobilista 2 in VR. The current implementation and the existing PRs from fholger don't work for AMS2 so I did a little digging. AMS2 / PC2 (Madness Engine) might be a bit of an oddity as you can only load it through Steam for VR mode and the dxgi.dll and d3d11.dll libraries are supplied through SteamVR (or at least are loaded from the Steam folder). This means that the correct name for injecting the ReShade dll doesn't work. However using opengl32.dll does allow it to be loaded, even though it's not an opengl game.
Additionally it uses some old OpenVR helper functions to initialise and submit that aren't caught by the current hooks. I've added new hooks to allow ReShade to load and apply shaders to …
=> Updates for VR support in Madness engine games such as AMS2

source/effect_symbol_table.cpp, source/effect_symbol_table_intrinsics.inl
* fix missing mul(scaler, mat2x4) intrinsic overload
* add transpose(non-square-matrix) intrinsics
* add new rule for type ranking, remove compatibility for matrix trunc
btw, I meant to ask is `input.cpp` has the correct encoding? 
git clone always ends up with errors with `u8"OEM ß"` `u8"Ü"` etc.
also `runtime_vk.cpp` is missing reference to `api::format_to_typeless(...)` from `reshade_api_format_tuils.hpp`
=> update some intrinsic

.gitignore, res/exports.def, source/windows/dinput8.cpp
There was one dedicated method left if forgot to add into the hook. There are some other ones but they seem to be shared by OLE com interface but i guess they are not needed.
Sorry for the recreation of the pull request. Wanted to clean up that git mess I created...
=> Added missing dinput8 method (GetdfDIJoystick)

source/effect_symbol_table_intrinsics.inl
template: `tex2Dgather#(sampler2D s, float2 uv, int2 offset0, int2 offset1, int2 offset2, int2 offset3)`
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/t2d-gatherred-s-float-int2-int2-int2-int2-
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureGatherOffsets.xhtml
https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpImageGather with `ConstOffsets`
the function provides performance gain similar to `tex2Dgather#(sampler2D s, float2 uv)` but with ability to address texels not immediate neighbor.
=> Add Gather overload

source/d3d10/d3d10_impl_swapchain.cpp, source/d3d10/d3d10_impl_swapchain.hpp, source/d3d11/d3d11_impl_swapchain.cpp, source/d3d12/d3d12_impl_swapchain.cpp, source/opengl/opengl_impl_device.cpp, source/opengl/opengl_impl_swapchain.cpp, source/openvr/openvr.cpp, source/runtime_gui.cpp, source/runtime_gui_vr.cpp, source/vulkan/vulkan_impl_swapchain.cpp
I could restore the VR functionality(DX11) in the latest source code to work again after the render target rework (commit ebf94113 ) It was caused that the backbuffer_resolved was not set on the vr submit for DX11.
After it tool a long time today to find the culprit I could start to work on serveral issues I encountered on VR with reshade:
- Fixed round errors would cause that the VR backbuffer is recreated very often and causing the left eye to flicker or black out completly
- Fixed OpenGL implementation pass the proper texture type. Now Google Earth works with reshade and other opengl VR implementations
- Fixed texture format typless check on DX11 and DX12 causing to permanently recreate the VR backbuffer on some games.
There are still things left I want to fix but they might need more …
=> Several VR fixes, DX10 Support

source/imgui_widgets.cpp, source/imgui_widgets.hpp, source/ini_file.hpp, source/runtime.cpp, source/runtime.hpp, source/runtime_gui.cpp
Use cases:
* Recompression
* Upload to cloud storage
Examples:
.bmp to .png (with ImageMagick)
```ini
[SCREENSHOT]
PostProcessApplication=C:\Softwares\ImageMagick-7.1.0-portable-Q8-x64\convert.exe
PostProcessArguments="<TARGET>" -quality 90 "<DIR>\<STEM>.png"
```
Post-processing by script (with PowerShell)
```ini
[SCREENSHOT]
PostProcessApplication=C:\Program Files\PowerShell\7\pwsh.exe
PostProcessArguments=-File MyScript.ps1 -TargetScreenshotPath "<TARGET>"
```
=> Add screenshot file post-processing

source/d3d11/d3d11_impl_command_list.cpp
Stumbled upon this by chance; it breaks VR rendering in newer Unity games which use an array texture for submission.
=> Fix D3D11 src and dst layer arguments inverted in copy_texture_region

examples/04-texture_dump/dump_options.hpp, examples/04-texture_dump/dump_texture.cpp, examples/04-texture_dump/texturemod_dump.vcxproj, examples/05-texture_replace/replace_options.hpp, examples/05-texture_replace/texturemod_replace.cpp, examples/05-texture_replace/texturemod_replace.vcxproj
- Added options header to configure addon behavior
- Added option to switch between full hashing and TexMod hashing
- Added support for saving textures to a subdirectory
- Added support for saving PNG files
- Added saving texture hashes to a set for optimization purposes.
If a texture has already been dumped in the current session, then the dump function will not write it to disk again.
This could be further improved by reading the filenames from the texture subdirectory and loading the hashes into the set, preventing the addon from dumping textures that were dumped in a previous gameplay session.
Default behavior is to save PNG textures to `<reshade-dir>/texdump/<texture-hash>.png`
Optimization is enabled by default
- Added options header to configure addon behavior
- Added option to …
=> Add features to texture addons

source/runtime.cpp
Should help prevent bug where you switch between HDR and SDR but it uses a cached version of the shader with the wrong color space.
I haven't actually got round to setting up a compiler and building ReShade from source myself but this hopefully this is simple and obvious enough for someone else to see if it's correct and test it doesn't break everything.
=> Add color space to attributes string

source/runtime.cpp, source/runtime.hpp, source/runtime_gui.cpp
Users can use this option for always select the specific preset on startup.
Use cases
* Daily preset editing
* Reset long distance exploring between base path to last selection
* Load reduction on loading screens instead of NoReloadOnInit
~~And this PR contain a bugfix
Force insert relative path to relative path is broken~~
=> Add option to force preset selection on startup

include/reshade_api.hpp, source/runtime.hpp, source/runtime_api.cpp
~~This commit adds `set_save_preset_on_api_uniform_change_state` which sets the new runtime flag `_save_preset_on_api_uniform_change` to the specified value. By default `_save_preset_on_api_uniform_change` is set to true to keep the API functionality the same with previous API versions. The flag `_save_preset_on_api_uniform_change` is used in the `set_uniform_variable_*` methods to allow for a way to switch preset saving off when uniform variables are changed.~~
~~API methods have been added at the bottom to keep API interfaces binary compatible. The `_save_preset_on_api_uniform_change` member variable is also added at the bottom of the runtime type for this reason.~~
~~I've not added a get_... variant as by default the flag is true and the general use case is that it's switched off only …
=> Removed preset saving from uniform variable setters, added save_current_preset to public API

include/reshade_api.hpp, source/ini_file.hpp, source/runtime.cpp, source/runtime.hpp, source/runtime_api.cpp, source/runtime_gui.cpp, source/runtime_objects.hpp
This PR contains these changes
* Add `effect` scope (See [My add-on side](https://github.com/seri14/reshade-addons/compare/main...addon-uibind))
* ~Add API `bool has_effects_loaded()` to avoid touch _effects/_techniques/_textures/_uniforms while loading effects~
Cancelled. See https://github.com/crosire/reshade/pull/250#issuecomment-1478615159
* Increase text buffer size from 128 to 256 (for to_string(float4x4) requires at least 144 bytes)
* Display definition default value as hint instead of input text
=> Add effect scope for preprocessor definitions

source/runtime.cpp, source/runtime.hpp
The current mechanism causes the effect reload blocking mechanism to reset in case the bit depth changes an odd number of times. This change prevents the reload block from being reset within a frame.
=> Prevent effect reloads in case the bit depth of the back buffer changes odd number of times within a frame

source/input.cpp, source/input.hpp
For games that run their message loop on a different thread than presents the SwapChain, key repeats are currently altering the state of the `_keys[]` array after `reshade::input::next_frame (...)` runs.
<h2>This nullifies the logic that twiddles the bits here:</h2>
```cpp
for (uint8_t &state : _keys)
state &= ~0x08;
```
Thus, when the UI goes to sample `reshade::input::is_key_pressed (...)`, it sees **0x88** caused by key repeats and all keybinds in ReShade will randomly fire off multiple times causing the UI to toggle rapidly, thousands of screenshots to be taken, multiple copies of code saved when <kbd>S</kbd> is pressed, etc.
<h3>Simply holding down the <kbd>Home</kbd> key in the Microsoft Store version of Persona 5 currently results in this:</h3> …
=> Add protection against key repeats triggering keybinds

source/runtime_api.cpp, source/runtime_gui.cpp
This button helps saving adjustments the depth settings as preprocessor definitions.
However, I do not understand why the author of [DisplayDepth.fx](https://github.com/crosire/reshade-shaders/blob/8ebf737b9f8ab55b129f7729c05c20f9a56d2369/Shaders/DisplayDepth.fx) banned the interface to change setting values.
=> Add a button 'Save and complete adjustments'

source/runtime.cpp
This issue was introduced in 035903aad0818a6db70a6208b6f41ebd407d4d27 months ago. The two `preset.get()` were accidentally removed when removing the toggle annotation, and the key shortcuts could not be loaded into ReShade.
=> Fix technique shortcuts are not loaded

source/runtime.cpp
This change allows developers can resolve whether known add-ons are installed.
```
ADDON_ + Addon name
```
Definition examples:
* ADDON_GENERIC_DEPTH (Generic Depth)
=> Add add-on name definitions as marker for detecting add-on

include/reshade_api.hpp, source/runtime.hpp, source/runtime_api.cpp
See my add-on side https://github.com/cot6/reshade-addons/commit/c398194608edfc621dbdf0478f990c2e37abcbad?diff=unified&w=1
=> Added API 'reset_uniform_value' to allow add-ons can reset variables

source/dll_resources.cpp
This is for add-ons.
If the resource exists for desktop language but not equals with selected language or default, LoadString choices desktop one by language fallback. So ImGui will display characters outside of the glyph range.
=> Always refer English if language fallback occurs

include/reshade.hpp, source/addon.cpp, source/ini_file.cpp, source/ini_file.hpp, source/runtime_api.cpp
This PR also includes the following changes:
[Fixed an issue where the file may be cached by different paths separately](https://github.com/crosire/reshade/commit/b94b1ee604871ddea30260a855c51e5c3c781d78)
=> Add the API to read all elements of value from ReShade configuration

source/dxgi/dxgi.cpp
Properly sets `BufferUsage` based on `buffer.flags` when calling `addon_event::create_swapchain`
=> fix(dxgi): apply DXGI_USAGE_SHARED correctly

source/windows/ws2_32.cpp
I noticed that the socket error state wasn't preserved. When addon is enabled, some operations might clobber `errno` and calling `is_local_socket` might change the `WSAGetLastError` value.
As stated on the [Windows documentation](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsagetlasterror):
> The WSAGetLastError function returns the last error that occurred for the calling thread. When a particular Windows Sockets function indicates an error has occurred, this function should be called immediately to retrieve the extended error code for the failing function call.
For instance, creating a string might clobber the error value as mentioned here: https://dolp.in/pr3143
This PR aims to limit hooking side-effects and preserves the socket error state.
=> Preserve socket error state

include/reshade_api.hpp, source/runtime.cpp, source/runtime.hpp, source/runtime_api.cpp
See my add-on side https://github.com/cot6/reshade-addons/pull/6 
TODO
=> Add API 'require_reload_effect' to set flag to reload effects

source/d3d10/d3d10_impl_command_list.cpp, source/d3d10/d3d10_impl_device.hpp, source/d3d11/d3d11_impl_command_list.cpp, source/d3d11/d3d11_impl_device_context.hpp
… if multiple "device_context_impl::push_constants()" calls were made between two draw calls.
While working on a RenoDX mod, I tried to push two separate cbuffers (with different reshade pipeline layouts and different cbuffers slots) within the same draw call (e.g. `addon_event::draw`) and noticed that the cbuffers values were cross polluting each other, the values of the second `push_constants()` call would end up set to the first cbuffer too.
So I checked the code and made a guess that the `ID3D11Buffer` might not be copied to the GPU immediately when calling (e.g.) `PSSetConstantBuffers()`, but later. Making separate copies of the buffer per cbuffer slot fixed the issue.
The command list from the game I was modding is not "deferred" afaik, but still I'm guessing some stuff is delayed, …
=> Fix DX11 *SSetConstantBuffers() calls setting the same buffer data to multiple cbuffers slots

source/runtime.cpp
fgets() generates a string ending with '\n', then all the empty lines cannot be skipped.
=> Fix linebreak performed by fgets() when loading .cube LUTs

res/exports.def, source/dll_main.cpp, source/input.cpp, source/input.hpp, source/runtime_gui.cpp, source/windows/dinput.cpp, source/windows/dinput8.cpp
I have added a new hook on `GetRawInputBuffer (...)` that classifies all input events as keyboard, mouse or gamepad and removes events from the buffer if ReShade is blocking that type of input.
This API does not use `WM_INPUT`, and cannot be captured through a game's message queue. It is intended for devices with high throughput where pulling `WM_INPUT` out of a window's message queue one by one is inefficient.
I would really like to see implementations of `is_blocking_mouse_input (...)` and `is_blocking_keyboard_input (...)` that do not acquire a lock. The fast-path to exit `GetRawInputBuffer (...)` when ReShade is not blocking input (99% of the time during gameplay!) is crippled by potential lock contention on an API designed specifically to alleviate locking overhead on extremely high …
=> Add GetRawInputBuffer hook to handle games that do not use WM_INPUT

source/runtime.cpp, source/runtime_internal.hpp
This work was to make my screenshot add-on always perform the depth capture.
.addonfx effects will no longer being affected by user choice directly, but you can still make it work like before by using the effects state API.
=> Allow add-on controlled effects to render regardless of effects state

source/runtime_gui.cpp
The labels were not unique before, so sometimes the button did not really reset the content, and the keyboard navigation was also buggy.
=> Fix reset buttons of preprocessors

source/runtime_manager.cpp
This PR implements a config option "MaximumRuntimes" that can be set in ReShade.ini to limit how many effect runtimes reshade will create. a Value of 0 (default) is unlimited runtimes.
Very useful for games that can produce secondary, non-game windows.
I'm not 100% on the naming and implementation details, this is my first PR to reshade.
=> Implement MaximumRuntimes option

include/reshade.hpp
- The `_HAS_CXX17` macro is undocumented and specific to MSVC - other compilers do not declare it. Using `__cplusplus` by itself is [also insufficient](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/) depending on compiler options. This means both checks are required :(
- `static_cast`ing a function pointer to `void *` is conditionally supported. MSVC allows it. Clang does not.
=> Improve support for non-MSVC compilers in addon API

examples/09-depth/generic_depth_addon.cpp
Hello,
Found a tiny little bug when I tried to select a specific depth buffer.
In the depth addon when "Match custom width and height exactly" is selected, the height filter is applied to the width
=> Fix height match on depth addon

source/d3d12/d3d12_device.cpp
This allows addons to properly track pipelines and their corresponding pipeline layouts. Zero-sized root signatures can be used for fixed vertex+pixel shaders, or empty compute shaders.
=> Pass zero-sized DX12 root signatures to add-ons

source/d3d12/d3d12_impl_device.cpp, source/d3d12/d3d12_impl_device.hpp
Avoid iteration per heap. Use ordered map instead
=> Optimize D3D12 GPU to original CPU descriptor handle

include/reshade_overlay.hpp
Fixes this issue when compiling addons:
```log
[build] In file included from C:\Users\clsho\Documents\GitHub\reshade\include/reshade.hpp:9:
[build] C:\Users\clsho\Documents\GitHub\reshade\include\reshade_overlay.hpp(842,125): error: too few arguments to function call, expected 2, have 1
[build]   842 | inline ImDrawList::ImDrawList(ImDrawListSharedData* shared_data) { imgui_function_table_instance()->ConstructImDrawList(this); }
[build]       |                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     ^
```
=> Fix ImDrawList constructor to accept shared_data
