crosire/reshade

source/runtime.hpp

Gave Reshade a new sexier default color palette.

New sexier default colors

---

source/gui.cpp

Now a more soothing less aggressive red.

Changed red tutorial color

---

source/gui.cpp
source/runtime.cpp
source/runtime.hpp
source/runtime_objects.cpp

https://reshade.me/forum/suggestions/4243-shift-right-click-to-reset-ui-variable

Shift + Right click to reset UI variable

---

source/gui.cpp
source/runtime.cpp

Fixed wrong output file path if screenshot path specified relative.

---

source/gui.cpp

This request contains these changes.
* Changed the implementation of "Active to top" to "Sort by used"
* When press "Sort by used", unused techniques will sorted by name

Change the implementation of "Active to top" to it does sorting by used

---

source/gui.cpp

Adds a button to clear the search bar. Only pops up when text was entered.

Add button to clear the search bar

---

source/ini_file.cpp
source/log.hpp

and fix coding the path of configuration

Fix logging the path it have utf8 characters

---

source/gui.cpp

For who trying to press the Shift+F2

Keep display the menu key until begin the tutorial

---

source/gui.cpp
source/runtime.cpp
source/runtime.hpp

Support additional preprocessor definitions from a preset

---

source/runtime.cpp

https://reshade.me/forum/shader-troubleshooting/5222-reshade-pixelsize

Fix lost precision of pixelsize macro definitions

---

source/gui_widgets.cpp

Fixed miscleanup of the "list" UI

---

source/gui.cpp

current code mean available width minus one pixel

Fix wrong calculate of width

---

source/gui.cpp
source/runtime_objects.hpp

and change the sorting to ignore case

Fix slow sorting of technique list

---

source/effect_preprocessor.cpp

Fixed mistake that ignore the last token when parsing

---

source/gui.cpp

For who regularly use the Home key

Changed to not show/hide the UI when editing text

---

source/d3d10/runtime_d3d10.cpp
source/d3d11/runtime_d3d11.cpp
source/d3d12/runtime_d3d12.cpp
source/d3d9/runtime_d3d9.cpp
source/effect_codegen_glsl.cpp
source/effect_codegen_hlsl.cpp
source/effect_codegen_spirv.cpp
source/effect_expression.hpp
source/gui.cpp
source/opengl/runtime_opengl.cpp
source/runtime.cpp
source/runtime_objects.hpp

Add a button to show disassembled functions

---

source/gui.cpp
source/runtime.cpp
source/runtime.hpp

Add filter to preset selector

---

source/gui.cpp
source/runtime.cpp
source/runtime.hpp

And contain these changes
* Fix browse path when user quit input mode
* Extract the process of set current preset path to for ready to accept #140 changes

Keep showing preset selector if require to reload effects

---

source/gui.cpp
source/ini_file.cpp
source/ini_file.hpp
source/runtime.cpp
source/runtime.hpp

And change the line outputs to non-random for ini file.

Add I/O caching for ini files

---

source/runtime.cpp

https://github.com/crosire/reshade/pull/140#issuecomment-532074157
https://github.com/crosire/reshade/pull/140/commits/10bf6b9186fedc30a6c486d48aaff261386bd375#diff-82cf230afdb2a0d5174111e6f17548a5R961-R963
https://github.com/crosire/reshade/pull/140#issuecomment-532285003
https://github.com/crosire/reshade/pull/140/commits/244abfb7fb46e60f58dd1aac1f8d6c259527f55e#diff-82cf230afdb2a0d5174111e6f17548a5L963-L965

Fix misoperation

---

source/ini_file.hpp

Add support the move semantics for these codes.
https://github.com/crosire/reshade/blob/beed18257129f2ae1ec962caabae59f7f7ae9c44/source/runtime.cpp#L1109-L1110
And same changes for path type. 
https://github.com/crosire/reshade/blob/beed18257129f2ae1ec962caabae59f7f7ae9c44/source/ini_file.hpp#L88-L91

Fixed the move semantics did not work

---

source/ini_file.cpp

The feature of cache and lazy-writing is working for INI files.
But if terminating the game between open and close(flush), the file size becomes 0.

Hotfix a case that the data may be lost if terminate a game while saving

---

source/gui.cpp
source/runtime.cpp
source/runtime.hpp
source/runtime_objects.hpp

Pressing the shortcut will cycle through all the possible values of that variable.

Shortcut keys for the shader exposed variables of types: bool, combo, list and radio.

---

source/d3d10/d3d10.cpp
source/d3d11/d3d11.cpp
source/dxgi/dxgi.cpp
source/dxgi/dxgi_swapchain.cpp

…systems where render GPU != display GPU.
This affects all MSHybrid laptops, in addition to some desktop setups.

Fixed crashes when switching between fullscreen and windowed on multi GPU.

---

source/runtime_gui.cpp

Use ImGui feature instead of user code

Use placeholder for search

---

source/runtime_config.cpp

```ini
[APP]
ForceColorFormat=2,,3,4,,5,6
```
-> `APP.ForceColorFormat[0..2] = "2,3", "4,5", "6"`

Support comma character in INI elements

---

source/runtime.cpp
source/runtime_gui.cpp
source/runtime_objects.hpp

Demo [Video](https://www.youtube.com/watch?v=uzkrY9596Yk) and [Code](https://gist.github.com/seri14/fc98066cfcda687da224d3f65e205413)

Add special variables ui_active/ui_hover

---

source/d3d12/runtime_d3d12.cpp

Changes root signature to not use sampler or srv/uav when not present.

Fix dx12 not allows effect without any texture or sampler

---

source/dll_main.cpp

* Enumerate through adapters and selected supported gpu.
* Lower d3d12 feature level to 11 for older hardware.

ReShade App Compatibility for d3d12

---

source/input.cpp

Fix compiler error when current user codepage not supporting German characters.
bom for VS to auto detect the file as utf-8.

change input.cpp encoding from ISO-8859 (28591) to utf-8 with BOM

---

setup/ReShade Setup.csproj

Ended up closing the last PR since I decided to delete the commit as to not dirty up the git history.
This *just* changes `TargetFrameworkVersion` to `v4.6.2`.

Bumped setup project to .NET Framework 4.6.2

---

include/reshade_api_device.hpp
include/reshade_api_resource.hpp
include/reshade_events.hpp
source/d3d9/d3d9.cpp
source/dxgi/dxgi.cpp
source/dxgi/dxgi_swapchain.cpp
source/vulkan/vulkan_hooks_device.cpp

Added swapchain_desc to create_swapchain event in order to have more control over the creation of the swap chain (required for enabling HDR in applications)

Added swapchain_desc

---

source/runtime.cpp
source/runtime_gui.cpp

Since I do not have Visual Studio installed on my machine, I haven't been able to test my changes out, and I do apologise for that potential difficulty.  However, I believe they are trivial enough to not require much maintenance down the line.  Thanks in advance for the response!

Added new macro-string extensions for the time, updated macro-string tooltip text to go along with it!

---

deps/Windows.props
source/runtime.cpp
source/runtime.hpp
source/runtime_gui.cpp

Probably in most cases, Users set the camera sound.

Play sound when taking screenshot

---

include/reshade_api.hpp
include/reshade_events.hpp
source/runtime.cpp
source/runtime.hpp
source/runtime_api.cpp
source/runtime_gui.cpp

[See my add-on code (seri14/reshade-addons)](https://github.com/seri14/reshade-addons/compare/addkind-techniquesort)

Add API event "sort_techniques" called when sorting techniques

---

source/runtime.cpp
source/runtime.hpp
source/runtime_gui.cpp

Users can use this macro to avoid overwriting already saved file when saving

Add macro of screenshot/postsavecommand %Count% and %Rotate%

---

source/dxgi/dxgi_swapchain.cpp
source/vulkan/vulkan_hooks_device.cpp

Enumerate color space for Vulkan during swapchain dump + log color space when calling IDXGISwapChain3::SetColorSpace1

---

source/runtime_gui.cpp

Add ability to describe sliders and "drag sliders"

---

source/effect_parser_stmt.cpp
source/effect_token.hpp

Fixes building effect_* files with GCC13.

Add missing includes for fx compiler for GCC13

---

include/reshade_api.hpp
include/reshade_events.hpp
source/ini_file.cpp
source/runtime.cpp
source/runtime.hpp
source/runtime_api.cpp
source/runtime_gui.cpp

See my add-on side https://github.com/cot6/reshade-addons/compare/addon-adjustdepth#diff-ea12865d5d197112b8d8c060751e5a0dfdeb5571ccb29f1e7400ef97904052a2R40

Add event 'reshade_overlay_uniform_variable'

---

source/runtime_gui.cpp

Fixed font rendering was offset by less than a pixel

---

source/runtime_api.cpp

Fixed effect scope not handled

---

source/runtime_gui.cpp
source/runtime_objects.hpp

See https://github.com/crosire/reshade-shaders/pull/247/commits/c3f1e5b20089054a6fd2a17459c62bba4b7a3e06 of https://github.com/crosire/reshade-shaders/pull/247

Add variable annotation 'ui_category_toggle'

---

include/reshade_api_pipeline.hpp
include/reshade_events.hpp
source/d3d12/d3d12_device.cpp

Adds event which allows addons to modify pipeline layouts (D3D12 Root Signatures).

Add create_pipeline_layout addon event

---

source/runtime.cpp

Sorry I missed testing the Adjust Depth.

Invalid STL handling if all effects are required to reload

---

source/runtime_api.cpp

e.g. `reshade-shaders\Shaders\Deband - コピー.fx`
In the case of a Japanese user copied a file to the same folder using Windows Explorer.

Error occurs due to a filename containing characters which does not match Unicode with current codepage

---

include/reshade_overlay.hpp

the upstream change:
https://github.com/ocornut/imgui/commit/914fbcf2e52d43db71d13f12f1a9971719f1c560#diff-cbc47f9fc55eb2c19b4be92d1c1e137bb8b72d072588ab3cb4bcba88576d14cbL3483

fix imgui related stuff not compiling under clang because of upstream change

---

source/runtime_gui.cpp

Fixed an issue where the Log tab would prevent users from switching to other tabs when new log messages were being written to the log file.
The log display was reloading the entire log content every frame when new messages arrived, which interfered with ImGui's tab switching mechanism.
Added a simple check to defer log reloading when the user is actively interacting with UI elements (clicking tabs, etc.). The log still updates in real-time, but not during UI interactions.
- Modified `draw_gui_log()` in `source/runtime_gui.cpp`
- Added `!ImGui::IsAnyItemActive() && !ImGui::IsAnyItemFocused()` condition before log reloading
- Added explanatory comments
- Tab switching now works properly even when new log messages are being written
- Log content still updates automatically when not …

Fix: Prevent Log tab from blocking tab switching when new messages arrive
